### PR TITLE
fix: docs vendor/ paths

### PR DESCRIPTION
**Pull request by dkarlovi**

### CODE REVIEW

**Comment by dantleech** [comment]
this was intentional as these examples are intended to be copy/pasted from the docs: https://php-tui.github.io/php-tui/docs/reference/widgets/block

granted that still makes some assumptions but I think it's less confusing then having `__DIR__ . '/../../../` in each example ?

**Comment by dkarlovi** [comment]
The issue is they don't work if you fork the repo, go to the folder and run them.

**Comment by dantleech** [comment]
I run them as `php examples/docs/foo/foo.php`

but happy to merge this, having the `require` in the examples at all is a bit weird and it would be better to hide it

**Comment by dantleech** [comment]
conflcits..

**Comment by dkarlovi** [comment]
Let's just close here and rethink then, not a big issue but it's the first touch with the repo and it not working was unexpected. :)

**Comment by dantleech** [comment]
also happy to use __DIR__

**Pull request closed without merging**
