### PR TITLE
Fix: Glyph with negative offset getting truncated.

### PR DESCRIPTION
**Pull request by KennedyTedesco**
Fix: https://github.com/php-tui/php-tui/issues/37

The idea is to check the last rows of the bitmap. For example:

```
STARTCHAR y
ENCODING 121
SWIDTH 576 0
DWIDTH 6 0
BBX 6 10 0 -2
BITMAP
00
00
00
88
88
98
68
08
88
70
```

Because this glyph has a `-2` offset, indicating a descent of 2, we examine the last two rows of the bitmap to see if there's a negative offset. If there is, we adjust `$yOffset` accordingly when rendering the character.

### CODE REVIEW

**Comment by dantleech** [comment]
I think we rather want to just make it render according to the bounds? So if you position it at 0,0 then "-2" would be 0?

**Comment by dantleech** [comment]
It could also be a strategy - it's the diff between trying to fit the font in the minimal vertical space and expanding the space to accommodate the possible bounds

**Comment by KennedyTedesco** [comment]
@dantleech You're more familiar with this part than me, I'm going to let you deal with it, for now, hahah I'm curious to see what strategy will you use. o/

**Comment by KennedyTedesco** [comment]
@dantleech I've pushed some changes, with my original idea for this fix. =D

**Comment by dantleech** [comment]
I think the problem is that this approach will not render the fonts as intended:

image

and see how the terminal renders fonts:

image

i.e. we need to take into account the full range so that letters such as `e` don't actually start at 0

**Comment by dantleech** [comment]
btw just FYI I refactored the shapes to decouple the "painting" responsiblity from the shape data, so this logic is currently in `TextRenderer`

**Comment by KennedyTedesco** [comment]
> by the way - FYI I refactored the shapes to decouple the "painting" responsiblity from the shape data, so this logic is currently in `TextPainter`

Nice!

**Comment by KennedyTedesco** [comment]
> I think the problem is that this approach will not render the fonts as intended:

Yeah, this needs another approach indeed. I'll give it a shot over the weekend. But, if you plan to work on this in the meantime, feel free.

**Comment by dantleech** [comment]
It already renders OK if the canvas is large enough, maybe it's fine 🤷

**Comment by KennedyTedesco** [comment]
In my tests with different canvas sizes, still truncating at bottom base :sweat_smile:

**Comment by dantleech** [comment]
image

note above it's fine where the canvas bounds can accomodate the "negative" offsets. there's a chance this is the "correct" way to do it.

**Comment by KennedyTedesco** [comment]
@dantleech Nice!

The other day, I tested starting the `$yOffset` at `0`, and then changing the canvas size made things accommodate very well.

```diff
@@ -67,7 +67,7 @@ class TextRenderer implements ShapePainter
         $charWidth = $shape->scaleX;
         $charHeight = $shape->scaleY;

-        $yOffset = $glyph->boundingBox->offset->y * $shape->scaleY;
+        $yOffset = 0;

         $points = [];
         foreach ($grid as $row) {
```

**Pull request closed without merging**
